name: testspace

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
  
    runs-on: ${{ matrix.runs-on }}

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Build Dist
      run: npm run build

  deploy:
    needs: build
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
  
    runs-on: ${{ matrix.runs-on }}

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Build Dist and Deploy
      run: npm run deploy

  test:
    needs: [build, deploy]
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
  
    runs-on: ${{ matrix.runs-on }}

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Build Dist and Deploy
      run: npm run deploy
      
    - name: Run Tests
      run: npm run test