name: testspace

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'

    - name: Install dependencies
      run: npm install

    - name: Build Dist
      run: npm run build

  deploy:
    needs: build
    container:
      image: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'

    - name: Install dependencies
      run: npm install

    - name: Build Dist and Deploy
      run: npm run deploy

    - name: Run Tests
      run: npm run test

  test:
    needs: deploy
    container:
      image: ${{ deploy.outputs.container }}
    
    steps:
    - name: Run Tests
      run: npm run test
