name: build

on:
  push:
    branches:
      - development

jobs:
  build:
    strategy:
      matrix:
        node-version: [latest]
        runs-on: [ubuntu-latest]
  
    runs-on: ${{ matrix.runs-on }}

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Build Dist
      run: npm run build

  deploy:
    needs: build
    strategy:
      matrix:
        node-version: [latest]
        runs-on: [ubuntu-latest]
  
    runs-on: ${{ matrix.runs-on }}

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Build Dist and Deploy
      run: npm run deploy

  test:
    needs: [build, deploy]
    strategy:
      matrix:
        node-version: [latest]
        runs-on: [ubuntu-latest]
  
    runs-on: ${{ matrix.runs-on }}

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Build Dist and Deploy
      run: npm run deploy
      
    - name: Run Tests
      run: npm run test

  publish:
    needs: [build, deploy, test]
    strategy:
      matrix:
        node-version: [latest]
        runs-on: [ubuntu-latest]
  
    runs-on: ${{ matrix.runs-on }}

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build Dist
        run: npm run build

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Pub Docker Image
        run: npm run ghcr_pub